### ISSUE TITLE
Breaking changes in a minor release! (1.3.0)

### ISSUE THREAD

**Issue by Expurple** [MathNya/umya-spreadsheet#207]
I updated from 1.2.7 to v1.3.0 and the build failed. This is because #204 introduced many breaking changes:

- Removed public `umya_spreadsheet::writer::csv::XlsxError`
- Removed public `umya_spreadsheet::writer::xlsx::XlsxError` (my code references it)
- Removed public `umya_spreadsheet::reader::xlsx::XlsxError` (my code references it)
- Changes to variants of public `CellRawValue`
- Added parameter to public `CellValue::set_error`
- Maybe something else? Consider running [cargo-semver-checks](https://github.com/obi1kenobi/cargo-semver-checks) against your pull requests to get a more accurate list.

Please consider yanking 1.3.0 from crates.io and releasing version 2.0.0 to reflect the breaking changes.

**Comment by MathNya** [comment]
@Expurple 
We apologize for any inconvenience caused.
We will respond to your suggestion.

**Comment by MathNya** [comment]
We have responded here.
Click here to see the results from cargo-semver-checks.
https://github.com/MathNya/umya-spreadsheet/blob/master/CHANGELOG.md

**Comment by schungx** [comment]
I have a different opinion on this... appreciate that you hear me out.

I understand that, technically speaking, we should not break public API on minor versions.

However, you'll find that it is bound to happen when dealing with something like this repo, which exposes the API of a very complex object.  We have a _large_ number of public types that must all remain _unchanged_ forever, lest we introduce a breaking change.

If we're bound to not breaking public API, that means that many small changes must then necessitate a major version bump.  Which means that, before long, we'll be on version `42.0.0` or something.

Of course, it would have been better to not release a `1.0` until _everything_ is stable...  but then to the user it doesn't really matter because they're constantly faced with code breakage anyway.  It doesn't make it any different from having 1.x versions that break code.

So, I suggest staying onto version 1.x but state clearly that the semver guarantees are not upheld here and public API's are free to change.  We can revise this policy when the API is complete and we can then bump it to `2.0`.  Then we can start following semver strictly again.

**Comment by agentjill** [comment]
> I personally don't need #204 right now, so I don't mind. I just want to get a fix to #200 wihout confusing `cargo`.

@Expurple , I understand your sentiment. But, understand that properly representing errors ( for cell error like `#REF!` etc. in #204 ) is key to my use case. Therefore I implemented the same. I properly prefaced the PR for breaking changes. Also other than errors, changes to `CellRawValue` i.e. removal of some Variants, don't lead to any code changes.

**Comment by Expurple** [comment]
You made a good contribution and I agree that the breakage isn't that big. I was able to update my code fairly quickly. IMO, @MathNya made the right call with 2.0.0 and nothing should be changed now.

So, I'm not actively asking to revert #204. I just mentioned this possibility as a less-terrible alternative to releasing a breaking 1.3.0, in a universe where the community doesn't want 2.0.0 today. I'm OK with 2.0.0 today.

**Comment by schungx** [comment]
> Also other than errors, changes to `CellRawValue` i.e. removal of some Variants, don't lead to any code changes.

Removal of variants would be a breaking change because code may have `match` statements with those variants in them (such as mine).

**Comment by Expurple** [comment]
If everyone is OK with 2.0.0 so far, I'm going to close the issue. Feel free to continue the discussion and reopen if necessary

**Comment by agentjill** [comment]
> > Also other than errors, changes to `CellRawValue` i.e. removal of some Variants, don't lead to any code changes.
> 
> Removal of variants would be a breaking change because code may have `match` statements with those variants in them (such as mine).

Sorry for miscommunication, by code I meant repo code not user code.
