### ISSUE TITLE
Non-standard-address

### ISSUE THREAD

**Issue by bhanutejaperumandla** [MathNya/umya-spreadsheet#79]
```Non-standard address
thread 'main' panicked at 'Non-standard address', /Users/XXXX/.cargo/registry/src/github.com-xxxxxxxxx/umya-spreadsheet-0.8.3/src/structs/address.rs:41:13
```

I get this error when I try to read few files (not all) using `umya_spreadsheet::reader::xlsx::read()`
when I copy the sheet content through excel and paste it in new excel file, it is read without any fail.
Can someone please help with this

**Comment by MathNya** [comment]
Thank you for contacting us.
Hmmm, perhaps the error is caused by an unexpected value being passed when reading the Excel file.
We will investigate the cause.
Please provide us with the Excel file that causes the error, or the characteristics of the file, detailed error information, etc., to the extent possible.
